rm(list=ls())
library(data.table)
setwd("F:/DataMining/R/diabetes")
load("data/output/na_clean_Data.rda")

#3给出各个变量的正常区间MIN-MAX
max_min_set=na_clean_Data
max_min_set$AST_MAX=40
max_min_set$AST_MIN=8
max_min_set$ALT_MAX=40
max_min_set$ALT_MIN=5
max_min_set$ALP_MAX=150
max_min_set$ALP_MIN=40
max_min_set$GGT_MAX=50
max_min_set$GGT_MIN=7
max_min_set$TP_MAX=83
max_min_set$TP_MIN=50
max_min_set$ALB_MAX=54
max_min_set$ALB_MIN=34
max_min_set$GLB_MAX=35
max_min_set$GLB_MIN=20
max_min_set$A_G_MAX=2.5
max_min_set$A_G_MIN=1.1
max_min_set$TG_MAX=1.7
max_min_set$TG_MIN=0
max_min_set$CHOL_MAX=5.2
max_min_set$CHOL_MIN=0
max_min_set$HDL_C_MAX=1.55
max_min_set$HDL_C_MIN=0.91
max_min_set$LDL_C_MAX=3.6
max_min_set$LDL_C_MIN=2
max_min_set$BUN_MAX=8.2
max_min_set$BUN_MIN=2.9
max_min_set$CREA_MAX=104
max_min_set$CREA_MIN=45
max_min_set$UA_MAX=416
max_min_set$UA_MIN=142

max_min_set$WBC_MAX=10
max_min_set$WBC_MIN=4

max_min_set$RBC_MAX=5.5
max_min_set$RBC_MIN=3.5
max_min_set$HGB_MAX=160
max_min_set$HGB_MIN=110
max_min_set$HCT_MAX=50
max_min_set$HCT_MIN=35
max_min_set$MCV_MAX=95
max_min_set$MCV_MIN=82
max_min_set$MCH_MAX=31
max_min_set$MCH_MIN=27
max_min_set$MCHC_MAX=360
max_min_set$MCHC_MIN=320
max_min_set$RDW_CV_MAX=14.5
max_min_set$RDW_CV_MIN=11.5
max_min_set$PLT_MAX=300
max_min_set$PLT_MIN=100
max_min_set$MPV_MAX=11
max_min_set$MPV_MIN=7
max_min_set$PDW_MAX=8.2
max_min_set$PDW_MIN=2.9
max_min_set$PCT_MAX=0.1
max_min_set$PCT_MIN=0.3
max_min_set$NEUT_MAX=75
max_min_set$NEUT_MIN=40
max_min_set$LYMPH_MAX=50
max_min_set$LYMPH_MIN=20
max_min_set$MONO_MAX=10
max_min_set$MONO_MIN=3
max_min_set$EO_MAX=8
max_min_set$EO_MIN=0.4
max_min_set$BASO_MAX=1
max_min_set$BASO_MIN=0
max_min_set$GLU_MAX=6.11
max_min_set$GLU_MIN=3.89


#保存
save(max_min_set,file="data/max_min_set.rda")
load("data/max_min_set.rda")
